apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgresql.fullname" . }}-admin # service name 
  labels:
    app: {{ template "postgresql.name" . }} # app name 
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: {{ .Values.service.type }}
  # delcate service ports
  ports:
    - targetPort: pgadmin-port # reference to the container port by name
      port: {{ .Values.pgadmin.service.port }}
      nodePort: {{ .Values.pgadmin.service.nodePort }}

      # optional loadbalancer IP
      {{- if and (eq .Values.pgadmin.service.type "LoadBalancer") .Values.pgadmin.service.loadBalancerIP }}
      loadBalancerIP: {{ .Values.pgadmin.service.loadBalancerIP }}
      {{- end }}
  selector:
   app: {{ template "postgresql.name" . }} # app name
   release: {{ .Release.Name | quote }}