
replicas: 1

image:
  repository: mongo
  tag: 4.1.6-xenial
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  containerPort: 27017 # default mongodb port

service:
  type: NodePort
  port: 30041 # see GearEngine Port Range Table