apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gearengine-mongodb.fullname" . }}-configuration # config name 
  labels:
    app: {{ template "gearengine-mongodb.name" . }} # app name
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data: # environment vars TODO: use secrets in production
  MONGO_INITDB_ROOT_USERNAME: gearengine
  MONGO_INITDB_ROOT_PASSWORD: gearengine
---