kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "gearengine-mongodb.fullname" . }}-pv-volume # storage volume name
  labels:
    type: local
    app: {{ template "gearengine-mongodb.name" . }} # app name
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/db" # path of mongodb
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "gearengine-mongodb.fullname" . }}-pv-claim # storage claim name
  labels:
    app: {{ template "gearengine-mongodb.name" . }} # app name
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany # enable read-write
  resources:
    requests:
      storage: 5Gi # size of the storage