apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "postgresql.fullname" . }}-config # config-map name 
  labels:
    app: {{ template "postgresql.name" . }} # app name
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data: # environment vars TODO: use secrets in production
  POSTGRES_DB: gearengine
  POSTGRES_USER: gearengine
  POSTGRES_PASSWORD: gearengine
